repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
- repo: local
  hooks:
    - id: flake8
      files: '(app|tests)/.*\.py'
      name: flake8
      entry: flake8
      language: system
      types: [python]

    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]

    - id: check-requirements
      name: check-requirements
      entry: ./scripts/check-requirements.sh
      language: script
