version: 0.2

phases:
  pre_build:
    commands:
      - |
        if [ -n "$MANUAL_PIPELINE_BRANCH" ]; then
          echo Manual pipeline branch provided, checking out branch $MANUAL_PIPELINE_BRANCH
          git checkout $MANUAL_PIPELINE_BRANCH
        elif [ -n "$COMMIT_ID" ]; then
          echo Checking out to govuk_${ENVIRONMENT}_latest tag...
          git checkout tags/govuk_${ENVIRONMENT}_latest
        fi
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS
        --password-stdin $ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - |
        TAGS="-t $REPOSITORY_URI:latest -t $REPOSITORY_URI:pipeline_$EXECUTION_ID"
        if [ -n "$COMMIT_ID" ]; then
          COMMIT_ID=$(echo $COMMIT_ID | cut -c 1-7)
          TAGS="$TAGS -t $REPOSITORY_URI:commit_$COMMIT_ID"
        fi
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build $TAGS -f Dockerfile.eas-govuk-alerts
        --build-arg ECS_ACCOUNT_NUMBER=$ACCOUNT_NUMBER
        --build-arg AWS_REGION=${AWS_REGION:-eu-west-2}
        --build-arg RESOURCE_PREFIX=${RESOURCE_PREFIX:-eas-app} --no-cache .
  post_build:
    commands:
      - echo Building complete on `date`
      - echo Pushing the Docker image...
      - docker push --all-tags $REPOSITORY_URI
