version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python3-dev jq --fix-missing
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - make bootstrap
      - python test.py
  post_build:
    commands:
      - echo "No post build commands"
