version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python2-dev --fix-missing
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - make bootstrap && pip3 freeze && python3 --version && flask publish-with-assets
  post_build:
    commands:
      - echo "No post build commands"
