version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python3-dev --fix-missing
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - make bootstrap
      - echo printenv
      - aws sts get-caller-identity
      - curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
      - cd $GOVUK_DIR && . $VENV_GOVUK/bin/activate && flask publish-with-assets
  post_build:
    commands:
      - echo "No post build commands"
