version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python3 pip3 python3-dev jq --fix-missing
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - make bootstrap
      - pip3 install boto3 && pip3 freeze && python3 --version && python3 ./app/test.py
  post_build:
    commands:
      - echo "No post build commands"
