version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python pip python3-dev jq --fix-missing
      - pip install boto3
      - pip install os
  pre_build:
    commands:
      - echo "" > environment.sh
  build:
    commands:
      - make bootstrap
      - python .codepipeline/test.py
  post_build:
    commands:
      - echo "No post build commands"
