version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking out to govuk_${ENVIRONMENT}_latest tag...
      - git checkout tags/govuk_${ENVIRONMENT}_latest
  build:
    commands:
      - echo Deployment started on `date`
      - bash ./.codepipeline/deploy-service.sh --SERVICE govuk-alerts --RESOURCE_PREFIX ${RESOURCE_PREFIX:-eas-app}
