name: on-pr-into-main

permissions:
  contents: read

env:
  PYTHON_VERSION: 3.12

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Use specified utils version in PR
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        # Match `utils:blah` and get the blah
        run: |
          PR_UTILS_BRANCH=$(echo "$PR_DESCRIPTION" | grep -oP '`utils:\K[^`]+' || true)

          if [[ -n $PR_UTILS_BRANCH ]]; then
            echo "Going to use branch $PR_UTILS_BRANCH for utils"
            sed -i "s/emergency-alerts-utils\.git/emergency-alerts-utils.git@$PR_UTILS_BRANCH/" requirements_github_utils.txt
            cat requirements_github_utils.txt
          else
            echo "Leaving utils target as default"
          fi

      - name: Bootstrap Python app and run tests
        run: |
          export ENVIRONMENT='local'
          set -eu
          make bootstrap-for-tests
          make test
