name: pr-checks

on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Prerequisites
        run: |
          curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip'; unzip 'awscliv2.zip' && ./aws/install
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
          nvm install v16.14.0 && nvm use v16.14.0
          python3.9 -m pip install --upgrade pip wheel setuptools

      - name: Bootstrap Python app and run tests
        run: |
          export ENVIRONMENT='development'
          set -eu
          make bootstrap
          make test
